# Generated by Django 3.2 on 2021-07-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New product', max_length=100)),
                ('description', models.CharField(default='Description', max_length=350)),
                ('price', models.DecimalField(decimal_places=20, max_digits=100)),
            ],
        ),
    ]
