# Generated by Django 3.2 on 2021-07-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Some title', max_length=100)),
                ('description', models.TextField(default='Some description', max_length='255')),
                ('featured', models.BooleanField(default='True')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
