# Generated by Django 3.2 on 2021-07-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsbase', '0002_alter_base_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='featured',
        ),
    ]
