# Generated by Django 3.2 on 2021-07-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsbase', '0003_remove_base_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='featured',
            field=models.BooleanField(default='True'),
        ),
    ]
