# Generated by Django 3.2 on 2021-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsbase', '0004_base_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='summary',
            field=models.TextField(default='This is summary', max_length='100'),
        ),
    ]
