# Generated by Django 3.2 on 2021-05-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsbase', '0005_alter_base_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='featured',
            field=models.BooleanField(null=True),
        ),
    ]
