# Generated by Django 3.2 on 2021-07-01 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsbase', '0006_alter_base_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='description',
            field=models.TextField(default='New description', max_length='255'),
        ),
    ]
