# Generated by Django 3.2 on 2021-07-08 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productsbase', '0007_alter_base_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='base',
            old_name='number',
            new_name='price',
        ),
    ]
