# Generated by Django 3.2 on 2021-05-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsbase', '0009_base_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='featured',
            field=models.BooleanField(default='True'),
        ),
    ]
