# Generated by Django 3.2 on 2021-08-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='Name of this problem', max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
